class SeleniumPaymentConst:
    ACCOUNT_INPUT_ID = "Account"
    NAME_INPUT_ID = "Name"
    NUM_INPUT_ID = "cardnumber"
    MONTH_INPUT_ID = "month"
    YEAR_INPUT_ID = "year"
    CVV_INPUT_ID = "cvv"
    PAYMENT_AMT_ID = "payment"
    CONFIRM_CHECKBOX_ID = "confirm"
    SUBMIT_BUTTON_ID = "submitbtn"
